services:
  postgres:
    container_name: motorizen-postgres
    image: postgres:alpine
    env_file:
      - ./docker/.env.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: motorizen-postgres
    networks:
      - devcontainer_net
    profiles:
      - dev
      - all

  pgadmin:
    container_name: motorizen-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./docker/.env.pgadmin
    ports:
      - 5050:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - monitor
      - all

  redis:
    container_name: motorizen-redis
    image: redis:alpine
    env_file:
      - ./docker/.env.redis
    ports:
      - 6379:6379
    hostname: motorizen-redis
    networks:
      - devcontainer_net
    volumes:
      - redis_data:/data
      - /home/edimar/Projetos/MotorizenJavaEdition/docker/redis-entrypoint.sh:/home/redis/entrypoint.sh
      - /home/edimar/Projetos/MotorizenJavaEdition/docker/redis.conf:/tmp/redis.conf
    entrypoint: ["sh", "/home/redis/entrypoint.sh"]
    profiles:
      - dev
      - all

  redisinsight:
    container_name: motorizen-redisinsight
    image: redislabs/redisinsight
    env_file:
      - ./docker/.env.redisinsight
    ports:
      - 5530:5530
    volumes:
      - redisinsight_data:/data
    profiles:
      - monitor
      - all

  rabbitmq:
    container_name: motorizen-rabbitmq
    image: rabbitmq:management-alpine
    env_file:
      - ./docker/.env.rabbitmq
    hostname: motorizen-rabbitmq
    networks:
      - devcontainer_net
    ports:
      - 5672:5672
      - 15672:15672 # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    profiles:
      - dev
      - all

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  devcontainer_net:
    external: true