server:
  address: 127.0.0.1
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: motorizen-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations:
      - db/migrations
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: ERROR
    '[com.efscode.motorizen_backend]': ERROR

app:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:3600}
      secret: ${JWT_SECRET}
